### ISSUE TITLE
Rename commands?

### ISSUE THREAD

**Issue by lazarljubenovic** [storybooks/vue-cli-plugin-storybook#20]
The naming convention of using colons seems inverted here. It makes more sense to me to be `storybook:serve` and `storybook:build` than the current inverted. What do you think?

**Comment by pksunkara** [comment]
`vue-cli-plugin-electron-builder` uses `serve:electron` and `build:electron`. I just followed that convention. I wanted all the `build` jobs to have `build` prefix regardless of what they are building, that way it's faster to identify, rather than reading `storybook` first and then `build`.

I am open to changing this if you can convince me with a major reason.

**Comment by lazarljubenovic** [comment]
Hm, I'd like all storybook commands in one place. Building the app, building storybook and building documentation are barely coupled at all, I don't see a reason why they'd be together. I see storybook as the category and we go deeper on each `:`, asking what do you want to do with the storybook.

It doesn't really matter, it's easy to rename. :smile:
