### ISSUE TITLE
not worked with vue-cli-plugin-svg-sprite

### ISSUE THREAD

**Issue by acopalipsis** [storybooks/vue-cli-plugin-storybook#39]
Not worked with [vue-cli-plugin-svg-sprite](https://github.com/swisnl/vue-cli-plugin-svg-sprite).
Demo - https://github.com/acopalipsis/svg-bug-demo
I really hope For your help.

UPDATE REPO

> WARNING in ./src/assets/icons/baseline-error_outline-24px.svg
Module build failed (from ./node_modules/svg-sprite-loader/lib/loader.js):
ExtractPluginMissingException: svg-sprite-loader exception. svg-sprite-loader in extract mode requires the corresponding plugin

> @ multi ./node_modules/@storybook/core/dist/server/config/polyfills.js ./node_modules/@storybook/core/dist/server/config/globals.js ./config/storybook/config.js (webpack)-hot-middleware/client.js?reload=true

**Comment by fapspirit** [comment]
Hello!
This warning happens due to `vue-cli-plugin-storybook` filtering all the plugins according to the internal list of allowed plugins. There is functionality to manually extend this list through `pluginOptions` described in [README.md](https://github.com/storybooks/vue-cli-plugin-storybook#usage), but it isn't published to npm yet.

@pksunkara can you publish it please?

**Comment by pksunkara** [comment]
This was done long ago. Should work now.
